### ISSUE TITLE
Improve some English texts

### ISSUE THREAD

**Issue by waviaei** [kuno1/hakama#12]
There few places where English are a bit odd.

- [ ] footer-entry.php line 13. Possibly => Subscribe to our Newsletter!
https://github.com/kuno1/hakama/blob/959938b4009302efdc9c4457ac9747831653db9b/footer-entry.php#L11-L14

- [ ] footer-entry.php line 16. Possibly => Subscribe to our newsletter for the latest updates and early access our new features.
https://github.com/kuno1/hakama/blob/959938b4009302efdc9c4457ac9747831653db9b/footer-entry.php#L15-L17

**Comment by fumikito** [comment]
Fixed! Thank you @waviaei
