### ISSUE TITLE
決済画面のカード情報入力フォーム異常

### ISSUE THREAD

**Issue by kzoou** [kuno1/hakama#21]
ステージング環境にて発生

1.カード情報入力フォームに入力が行なえない
2.ボタンラベルが「支払う」ではなく、「カートに入れる」になっている
![FireShot_Capture_017_-_支払い_–_Kunoichi_WP_Market_Place_-_ts-kunoichimarket-staging_click-2](https://user-images.githubusercontent.com/536501/74512544-e452e200-4f4b-11ea-8534-b4c49574ff71.jpg)

**Comment by fumikito** [comment]
オプションを変えたら大丈夫になりました。本番環境とステージングに設定の差があったようです。

WooCommerce > 設定 > 決済 > Stripe > 「インラインクレジットカードフォーム」
