### ISSUE TITLE
GA用カスタムディメンション送信jsにセミコロンが抜けている

### ISSUE THREAD

**Issue by kzoou** [kuno1/hakama#38]
商品詳細で出力しているGA用のjsにセミコロンが抜けている部分があります。

`;ga( "set", "dimension3", 1347 )ga( 'require', 'displayfeatures' );`

**Comment by fumikito** [comment]
@kzoou  修正しました。 
https://github.com/kuno1/makibishi/commit/4f01506b37a627e14090056b1c25c3ed69597221
