### ISSUE TITLE
FAQのログイン制限が有効にならない

### ISSUE THREAD

**Issue by kzoou** [kuno1/hakama#48]
FAQページの投稿画面でログイン制限を制御するメニューが動いてないようです。

![FireShot Capture 014 - 投稿の編集 ‹ Kunoichi Market — WordPress - kunoichiwp com](https://user-images.githubusercontent.com/536501/91530364-eb6c9b00-e945-11ea-8a50-9efd4f226de6.png)

制限なし、お客様、どちらを選択しても未ログインで閲覧可能になってしまいます。

**Comment by fumikito** [comment]
ステージングにリリースし、解決していることを確認。
